# Generated by Django 3.2.3 on 2021-05-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawled_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardData2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('ranking', models.CharField(max_length=5)),
                ('imgurl', models.URLField()),
                ('artist', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='BoardData',
        ),
    ]
