# Generated by Django 3.2.3 on 2021-05-31 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawled_data', '0008_alter_boarddata_ranking'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardData2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('ranking', models.IntegerField(default=0)),
                ('imgurl', models.URLField()),
                ('artist', models.CharField(max_length=200)),
            ],
        ),
    ]
