# Generated by Django 3.2.3 on 2021-05-31 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawled_data', '0010_auto_20210531_1557'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BoardData3',
            new_name='BoardData2',
        ),
    ]
